name: "Setup Ansible"
description: "A GitHub Action that installs Ansible and its dependencies."
inputs:
    version:
        required: true
        description: "The version of Ansible to install."
    python-version:
        required: false
        description: "If you wish to override the default version of python."
runs:
    using: "composite"
    steps:
        - name: "Install Python"
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python-version }}

        - name: "Cache python packages"
          uses: actions/cache@v4
          with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-${{ inputs.version }}

        - name: "Install Ansible"
          shell: bash
          run: |
              python -m pip install ansible==${{ inputs.version }}
